# Generated by Django 4.1.3 on 2022-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_system", "0002_wastemanagementcompany_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycustomer",
            name="subscribed_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
