# Generated by Django 4.1.3 on 2022-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_iroha_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="iroha_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
