# Generated by Django 4.1.3 on 2022-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_iroha_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcode"),
        ),
    ]
