# Generated by Django 4.1.3 on 2022-11-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("waste_system", "0002_wastemanagementcompany_owner"),
        ("users", "0004_user_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed_company",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="waste_system.wastemanagementcompany",
            ),
        ),
    ]
